@extends('layouts.page')
@section('title', 'School of Engineering - Home')
@section('content')
    @include('components.hero')
    @include('components.news-preview')
    @include('components.home-about')
    @include('components.courses-preview')
    @include('components.events-preview')
    @include('components.testimonials')
    @include('components.staff-preview')
@endsection
