@extends('layouts.page')
@section('title', 'School of Engineering - Home')
@section('content')
    @include('components.hero')
    @include('components.banner-feature')
    @include('components.news-preview')
    @include('components.call-to-action')
    @include('components.programs-preview')
    @include('components.home-about')
    @include('components.video-preview')
    @include('components.events-preview')
    @include('components.testimonials')
    @include('components.staff-preview')
@endsection
